### ISSUE TITLE
Suggestion de fonctionalités

### ISSUE THREAD

**Issue by RazielSama** [em-squared/5e-drs#42]
Hello !

Merci pour ton travail !

J'ai ici deux petites idées d'améliorations, je ne sais pas trop si c'est difficile à implémenter, mais je me lance tout de même: 

- Générateur de rencontre: Donner les PX à répartir entre les PJs
- Bestiaire: une infobulle quand on survole le monstre dans le tableau(liste) pour avoir un résumé du monstre, du genre [CA, PV, index de dangerosité, PX]

A bientôt !

**Comment by em-squared** [comment]
> Générateur de rencontre: Donner les PX à répartir entre les PJs
Ça devrait pas être trop compliqué

> Bestiaire: une infobulle quand on survole le monstre dans le tableau(liste) pour avoir un résumé du monstre, du genre [CA, PV, index de dangerosité, PX]
Tu parles de la liste du calculateur de rencontre ou du tableau des créatures ? Dans le tableau on peut déjà agrandir la ligne pour avoir tout le détail.

**Comment by em-squared** [comment]
Le calculateur de rencontre affiche maintenant le total de PX à distribuer aux PJ.

**Comment by RazielSama** [comment]
>> Bestiaire: une infobulle quand on survole le monstre dans le tableau(liste) pour avoir un résumé du monstre, du genre [CA, PV, index de dangerosité, PX]
>

> Tu parles de la liste du calculateur de rencontre ou du tableau des créatures ? Dans le tableau on peut déjà agrandir la ligne pour avoir tout le détail.
>
Effectivement, je parlais du tableau, pour ne pas avoir à déployer toute la fiche du monstre en fait.

>Le calculateur de rencontre affiche maintenant le total de PX à distribuer aux PJ.
>
Nice ! Idéalement je pensais plutôt à l'XP par joueur.

Par exemple, une rencontre à 5900XP total, 5 PJs, le calculateur donnera 1180XP/PJs.
Je sais pas si je m'explique bien x)

**Comment by em-squared** [comment]
Voilà, le calculateur affiche maintenant le montant de PX à distribuer par PJ pour les MJ qui veulent pas sortir la calculette.
Et une boîte s'ouvre au survol de tous les liens des créatures avec PV, CA, Dangerosité/PX et Caractéristiques.
