### ISSUE TITLE
pas de nothic

### ISSUE THREAD

**Issue by H4nriver** [em-squared/5e-drs#46]
j'ai constaté que le nothic n'est pas encore dans le bestiaire. Est-ce un oubli?
Site impeccable sinon! :)

**Comment by em-squared** [comment]
Salut,

>j'ai constaté que le nothic n'est pas encore dans le bestiaire. Est-ce un oubli?

C'est pas un oubli, le nothic n'est pas dans Héros & Dragons. Mais il est bien présent dans les _Basic Rules_, il est donc bien OGL. Donc soit BBE a choisi de ne pas l'inclure, soit c'est un oubli de leur part.

Je l'ajouterai pour faire bonne mesure. Merci pour le signalement !

>Site impeccable sinon! :)

Merci !
