### ISSUE TITLE
Erreur dans l'installation des dépendances

### ISSUE THREAD

**Issue by zolti1** [em-squared/5e-drs#49]
J'avais besoin d'une version hors ligne du DRS pour mes joueurs (on utilise H&D + Pangée), j'ai donc voulu me faire une version "logiciel" avec ElectronJS.

Il est a noté que je ne maitrise pas NodeJS (je l'utilise uniquement pour electron, nedb, asar), j'ai donc suivit la procédure indiqué et avec la première commande "yarn install", j'ai le résultat :

> yarn install v1.22.19
> info No lockfile found.
> [1/4] Resolving packages...
> warning @vuepress/plugin-google-analytics > @vuepress/types > @types/markdown-it > highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer 
> supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer 
> supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and 
> is no longer supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the 
> V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> warning axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
> error Couldn't find the binary git
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

j'utilise Node.js v16.15.0

Et à cause de la structure JS du site, on ne peut pas extraire une version "utilisable" (avec webcopy & co). C'est dommage, on va devoir rester sur haches & dés, même s'il n'y a pas les nouveaux éléments de Pangées.

**Comment by em-squared** [comment]
Je build avec node v14.20.0. Au delà, il y a effectivement des problèmes. Je te recommande d'utiliser nvm (https://github.com/nvm-sh/nvm) puis de faire : 
`rm -rf node_modules` pour supprimer toutes les libs déjà buildées avec node 16, sinon tu vas avoir des incompatibilités
`nvm install 14`
`npm install -g yarn`
`yarn install`
`yarn dev` pour vérifier que ça tourne bien
`export NODE_OPTIONS=--max-old-space-size=8192` (oui, le build consomme un max de ram à cause du nombre de page. vuepress scale pas bien)
`yarn build --dest=chemin/de/destination` pour builder la version statique

**Comment by zolti1** [comment]
node_modules purgé
Installation de Node 14.20.0 et 14.0.0 avec nvm

Il y a bien la prise en charge du changement de la version de node. Par contre, j'ai toujours le même résultat, même s'il y a des légères variantes dans les erreurs.

> node -v
> v14.0.0
> 
> yarn install
> yarn install v1.22.19
> info No lockfile found.
> [1/4] Resolving packages...
> warning @vuepress/plugin-google-analytics > @vuepress/types > @types/markdown-it > highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer 
> supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer 
> supported or maintained
> warning @vuepress/plugin-pwa > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and 
> is no longer supported or maintained
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> warning @vuepress/plugin-pwa > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the 
> V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> warning @vuepress/plugin-pwa > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> warning axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
> error Couldn't find the binary git
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by em-squared** [comment]
> error Couldn't find the binary git
Tu n'as pas git installé ? L'erreur indique qu'il ne le trouve pas.

**Comment by zolti1** [comment]
Réponse un peut tardive. J'ai msysGit d'installé.

**Comment by em-squared** [comment]
Connais pas msysGit. Ce que je vois, c'est que ça cherche git et que ça le trouve pas. Donc soit tu installes git, soit tu fais en sorte que msysGit réponde à 'git' dans la cli.

Si j'ai bien compris, tu es sur Windows, je n'ai hélas aucune idée de comment ça peut ou pas fonctionner sur cet OS.

**Comment by em-squared** [comment]
Tu t'en sors ? Tu as besoin d'une version statique déjà buildée prête à l'emploi pour ton wrapper Electron ?
