### ISSUE TITLE
Version PDF

### ISSUE THREAD

**Issue by hakooh33** [em-squared/5e-drs#50]
Bonjour,

Super boulot, hyper utile.
A des fins d'une première séance, je souhaitais savoir s'il existait une version PDF par exemple juste de la création de personnages.

Merci

**Comment by em-squared** [comment]
Bonjour,

Merci, il est possible d'imprimer toutes les pages du site en PDF.
Voici ce que donne la page de création de personnage par exemple : [Création de personnage PDF](https://drive.google.com/file/d/114ParxhyLW2OgGsNLiEImdgfj7Rt4E46/view?usp=sharing)

**Comment by hakooh33** [comment]
Ok, mais il y a un bouton pour le faire, car quand je fais clic droit imprimer il y a l'adresse du site en bas de page ?

**Comment by em-squared** [comment]
Pas de bouton, c'est la fonction impression du navigateur. Il y a des options pour retirer les en-têtes et pieds de page avec l'adresse du site.

**Comment by hakooh33** [comment]
Super je viens de repérer l'option pour les en-têtes et pieds de page, merci beaucoup pour l'astuce :-)
Et merci pour le reste !!!

**Comment by em-squared** [comment]
Avec plaisir :)
