### ISSUE TITLE
les extention

### ISSUE THREAD

**Issue by KradusYamie** [em-squared/5e-drs#53]
il serais bien d'avoir les information sur les extention tel que Mordenkainen Présente:
Les Monstres du Multivers ou Par-delà le Carnaval
de Sorcelume.
merci d'avance

**Comment by em-squared** [comment]
Si tu parles de publier les contenus présents dans ces ouvrages, ce n'est malheureusement pas possible. Il s'agit de contenu "product identity"qui ne sont pas sous licence OGL. Il n'est donc pas autorisé de les partager librement.
